platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'AdaloApp' do
  # Pods for AdaloApp
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNInAppBrowser', :path => '../node_modules/react-native-inappbrowser-reborn'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

  target 'AdaloAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  use_native_modules!
end

target 'AdaloApp-tvOS' do
  # Pods for AdaloApp-tvOS

  target 'AdaloApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
