default_platform(:ios)

platform :ios do
  desc "Update the plist of a project"
  lane :beta do |options|
    # puts "============================================================="
    # require 'pp'
    # pp options
    # puts "============================================================="

    bundle_id = options[:bundle_id]
    username = options[:username]

    match(
      app_identifier: bundle_id,
      username: username,
      type: "appstore",
    )
    
    match(
      app_identifier: bundle_id,
      username: username,
      type: "development",
    )

    update_project_provisioning(
      profile: ENV["sigh_#{bundle_id}_appstore_profile-path"],
      build_configuration: "Release"
    )

    gym(
      scheme: 'AdaloApp',
      export_method: "app-store",
      export_options: {
        method: 'app-store',
        provisioningProfiles: {
          bundle_id => "match AppStore #{bundle_id}"
        }
      }
    )

    upload_to_testflight(
      app_identifier: bundle_id,
      username: username,
    )
  end
end
