# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "ProtonPreviewer.xcodeproj")
    build_app(scheme: "ProtonPreviewer")
    upload_to_testflight
  end

  desc "Print latest uploaded build number"
  lane :buildnumber do
    build_number = latest_testflight_build_number(version: '0.3.1')
    puts "-------------> #{build_number}"
  end
end
